parameters:

    dineromail.api.endpoint: "https://checkout.dineromail.com/CheckOut"
    dineromail.controller.route.name: "dineromail_execute"
    dineromail.controller.process.route.name: "dineromail_process"

    dineromail.form.type.wrapper.class: "Mmoreram\\DineromailBundle\\Services\\Wrapper\\DineromailTypeWrapper"
    dineromail.routes.loader.class: "Mmoreram\\DineromailBundle\\Router\\DineromailRoutesLoader"