services:

    dineromail.form.type:
        class: %dineromail.form.type.class%
        arguments:
            payment.bridge: @payment.bridge
        tags:
            - { name: form.type, alias: dineromail_view }

    dineromail.manager:
        class: %dineromail.manager.class%
        arguments:
            payment.event.dispatcher: @payment.event.dispatcher
            payment.bridge: @payment.bridge

#    dineromail.twig.extension:
#        class: %dineromail.twig.extension.class%
#        arguments:
#          form.factory: @form.factory
#          payment.bridge: @payment.bridge
#          dineromail.config: %dineromail.config%
#        tags:
#          - { name: twig.extension }

    dineromail.routes.loader:
        class: %dineromail.routes.loader.class%
        arguments:
            dineromail.controller.route: %dineromail.controller.route%
            dineromail.controller.process.route: %dineromail.controller.process.route%
        tags:
            - { name: routing.loader }